language: python

# If your build needs more advanced behavior, see detailed Travis CI instructions:
# https://docs.travis-ci.com/user/languages/python/

python:
  - "3.7"

install:
  - pip install -r requirements.txt

# There aren't any tests (yet); just supplying a script to give the build something to do
script:
  - python -m unittest

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)